version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: /ecr-login.sh
  AfterInstall:
    - location: /docker-restart.sh

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user